### ISSUE TITLE
problems on M1

### ISSUE THREAD

**Issue by cmungall** [INCATools/oakx-grape#17]
When running `poetry run python -m unittest`

I get

```
======================================================================
ERROR: tests.test_plugin (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_plugin
Traceback (most recent call last):
  File "/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/cjm/repos/oakx-grape/tests/test_plugin.py", line 4, in <module>
    from oaklib.implementations import get_implementation_resolver
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_implementation_from_shorthand  # noqa:F401
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/oaklib/selector.py", line 8, in <module>
    from oaklib.implementations import GildaImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/oaklib/implementations/__init__.py", line 28, in <module>
    from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/oaklib/implementations/pronto/pronto_implementation.py", line 13, in <module>
    import pronto
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/pronto/__init__.py", line 24, in <module>
    from .definition import Definition
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/pronto/definition.py", line 5, in <module>
    from .xref import Xref
  File "/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/pronto/xref.py", line 6, in <module>
    import fastobo
ImportError: dlopen(/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so, 0x0002): tried: '/Users/cjm/Library/Caches/pypoetry/virtualenvs/oakx-grape-pUaGkv-X-py3.9/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by cmungall** [comment]
also reported here: https://github.com/fastobo/fastobo-py/issues/313

**Comment by cmungall** [comment]
If I do this

```bash
poetry export -f requirements.txt --output requirements.txt
pip install -r requirements.txt
```

then it builds the fastobo wheel rather than trying to use an existing (incorrect) one

**Comment by cmungall** [comment]
spoke to soon, still didn't solve it

```
✗ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastobo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so, 0x0002): tried: '/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
>>>
```

**Comment by cmungall** [comment]
```
✗ pip install fastobo
Collecting fastobo
  Using cached fastobo-0.12.1-cp39-cp39-macosx_12_0_arm64.whl
Installing collected packages: fastobo
Successfully installed fastobo-0.12.1
(oakx-grape-env) ➜  oakx-grape git:(main) ✗ ls /Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo*
/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so

/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo-0.12.1.dist-info:
COPYING       INSTALLER     METADATA      RECORD        REQUESTED     WHEEL         top_level.txt
```

**Comment by cmungall** [comment]
```
(oakx-grape-env) ➜  oakx-grape git:(main) ✗ conda install -c bioconda fastobo
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - fastobo

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by cmungall** [comment]
```
✗ file /Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so
/Users/cjm/opt/anaconda3/envs/oakx-grape-env/lib/python3.9/site-packages/fastobo.cpython-39-darwin.so: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by cmungall** [comment]
thanks to @hrshdhgd for help, still no further along

**Comment by cmungall** [comment]
@justaddcoffee shared his .so file, which looks like this:

```
✗ file ~/Downloads/fastobo.cpython-39-darwin.so
/Users/cjm/Downloads/fastobo.cpython-39-darwin.so: Mach-O 64-bit dynamically linked shared library arm64
```

I substituted that... and it works!

success... in some sense
